apiVersion: v1     # API Version
kind: Service      # Menambahkan object Service
metadata:          # menambahkan metadata 
  name: karsajobs  # nama
  labels:
    app: karsajobs # label
spec: # Ekspose port dengan tipe NodePort
  type: NodePort
  selector:
    app: karsajobs 
  ports:
    - port: 8080    
      targetPort: 8080 # container
      nodePort: 30001  # host